auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka:9092
    name: LocalKafka
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required
        username="user" password="password";
    readOnly: false
rbac:
  roles: []
webclient: {}
