server:
  port: 8001

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: io.craigmiller160.kafka.sync.consumer
    bootstrap-servers:
      - "localhost:29092"